question_data = [
    {"text": "The color of a polar bear’s skin is black.", "answer": "True"},
    {"text": "Bats are blind.", "answer": "False"},
    {"text": "Bananas grow on trees.", "answer": "False"},
    {"text": "Honey never spoils.", "answer": "True"},
    {"text": "Lightning never strikes in the same place twice.", "answer": "False"},
    {"text": "Goldfish only have a three-second memory.", "answer": "False"},
    {"text": "Adult humans have more bones than babies.", "answer": "False"},
    {"text": "Venus is the closest planet to the Sun.", "answer": "False"},
    {"text": "Humans share 50% of their DNA with bananas.", "answer": "True"},
    {"text": "The human brain is the heaviest organ in the human body.", "answer": "False"},
    {"text": "A day on Venus is longer than a year on Venus.", "answer": "True"},
    {"text": "The inventor of the Pringles can is buried in one.", "answer": "True"},
    {"text": "Water makes up approximately 80% of the human brain.", "answer": "True"},
    {"text": "An octopus has three hearts.", "answer": "True"},
    {"text": "Lightning is hotter than the surface of the sun.", "answer": "True"},
    {"text": "Ostriches stick their heads in the sand to hide from predators.", "answer": "False"},
    {"text": "A group of crows is called a murder.", "answer": "True"},
    {"text": "Penguins can fly.", "answer": "False"},
    {"text": "In Switzerland, it’s illegal to own only one guinea pig.", "answer": "True"},
    {"text": "Humans and dinosaurs coexisted.", "answer": "False"},
    {"text": "There are more stars in the universe than grains of sand on Earth.", "answer": "True"},
    {"text": "The Great Wall of China is visible from space.", "answer": "False"},
    {"text": "Sharks are mammals.", "answer": "False"},
    {"text": "Tomatoes are vegetables.", "answer": "False"},
    {"text": "An octopus can regrow a lost arm.", "answer": "True"},
    {"text": "The Mona Lisa has no eyebrows.", "answer": "True"},
    {"text": "Bees are found on every continent except Antarctica.", "answer": "True"},
    {"text": "A sneeze is faster than a cheetah.", "answer": "True"},
    {"text": "Humans have 206 bones in their bodies.", "answer": "True"},
    {"text": "Bananas are berries.", "answer": "True"},
    {"text": "Dolphins sleep with one eye open.", "answer": "True"},
    {"text": "Sound travels faster in water than in air.", "answer": "True"},
    {"text": "The Eiffel Tower can grow more than six inches in summer.", "answer": "True"},
    {"text": "Vikings wore helmets with horns.", "answer": "False"},
    {"text": "Hot water freezes faster than cold water.", "answer": "True"},
    {"text": "All starfish have five arms.", "answer": "False"},
    {"text": "The unicorn is the national animal of Scotland.", "answer": "True"},
    {"text": "Humans have 46 chromosomes.", "answer": "True"},
    {"text": "Octopuses lay 1000 eggs at a time.", "answer": "True"},
    {"text": "Elephants are the only animals that can't jump.", "answer": "True"},
    {"text": "The hummingbird is the only bird that can fly backward.", "answer": "True"},
    {"text": "The Eiffel Tower was originally intended for Barcelona.", "answer": "True"},
    {"text": "The longest recorded flight of a chicken is 13 seconds.", "answer": "True"},
    {"text": "A crocodile cannot stick its tongue out.", "answer": "True"},
    {"text": "Apples float on water because they are made of 25% air.", "answer": "True"},
    {"text": "A snail can sleep for up to three years.", "answer": "True"},
    {"text": "Humans lose about 50 to 100 hairs a day.", "answer": "True"},
    {"text": "The longest one-syllable word in English is 'strengths.'", "answer": "True"},
    {"text": "A human’s ears and nose never stop growing.", "answer": "True"},
    {"text": "There are more fake flamingos than real ones.", "answer": "True"}
]
